apiVersion: v1
kind: Service
metadata:
  labels:
    app: goodblast-be
  name: goodblast-be
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: goodblast-be
  sessionAffinity: None
  type: ClusterIP
