apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base
- ./ingress.yaml

labels:
- pairs:
    app: goodblast-be
    cluster: prod
  includeTemplates: true

replicas:
- count: 10
  name: goodblast-be

configMapGenerator:
- envs:
  - config/goodblast-be.env
  name: goodblast-be-cm

images:
- name: goodblast/goodblast-be
  newTag: TO_BE_CHANGED   # To be changed via the build.sh
